--- 
- name: Install apache and php 
  hosts: webserver
  become: yes
  tasks:
    - name: install apache2 
      apt:
        name: "{{ apache_package }}"
        update_cache: yes
        state: present 
    - name: install php packages 
      apt: 
        package:
          name: "{{ item }}"
          state: present
        loop: "{{ php_packages }}"
    - name: create info.php 
      copy:
        dest: "{{ info_page_path }}"
        src: "info.php"
      notify: 
        - Restart apache2
  handlers:
    - name: Restart apache2
      service: 
        name: apache2
        enabled: yes
        state: restarted

  

