--- 
- name: install apache and php packages
  hosts: webserver
  become: yes
  roles:
    - lamp

- name: install springpetclinic 
  hosts: appserver
  become: yes
  roles:
    - springpetclinic

- name: install tomcat9
  hosts: webserver
  become: yes
  roles:
    - squintans.tomcat9
